apiVersion: config.ratify.deislabs.io/v1beta1
kind: NamespacedStore
metadata:
  name: store-oras
spec:
  name: oras
  parameters: 
    cacheEnabled: true
    ttl: 10
    useHttp: true  
    authProvider:
      name: k8Secrets
      secrets: 
      - secretName: ratify-dockerconfig