# Check the documentation at https://goreleaser.com for more options
before:
  hooks:
    - go mod tidy
builds:
  - id: ratify
    dir: cmd/ratify
    binary: ratify
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: sbom
    dir: plugins/verifier/sbom
    binary: sbom
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
release:
  prerelease: auto
  draft: true
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
