apiVersion: v2
name: ratify
description: A Helm chart for Ratify
version: 1.11.0
appVersion: v1.0.0
home: https://github.com/deislabs/ratify
icon: https://raw.githubusercontent.com/deislabs/ratify/main/logo.svg
