image:
  repository: ghcr.io/susanshi/ratify
  crdRepository: ghcr.io/susanshi/ratify-crds
  tag: v11
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
ratifyTestCert: |
  -----BEGIN CERTIFICATE-----
  MIIDVjCCAj6gAwIBAgIBOzANBgkqhkiG9w0BAQsFADBaMQswCQYDVQQGEwJVUzEL
  MAkGA1UECBMCV0ExEDAOBgNVBAcTB1NlYXR0bGUxDzANBgNVBAoTBk5vdGFyeTEb
  MBkGA1UEAxMSd2FiYml0LW5ldHdvcmtzLmlvMB4XDTIyMTEwMTIwMzMyNVoXDTIy
  MTEwMjIwMzMyNVowWjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAldBMRAwDgYDVQQH
  EwdTZWF0dGxlMQ8wDQYDVQQKEwZOb3RhcnkxGzAZBgNVBAMTEndhYmJpdC1uZXR3
  b3Jrcy5pbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMH7SfZSMoA1
  NDDVVoO2Gnqv5+Ns63m/L6QDQiVFINS5gXFuqrYVU+qHiruiCpvI6rOVMSybusmV
  al5ev2uQ6FboQyp3G0XnHH7JQb+S4ORb70gcOUmejJPaWilEuaQkgCxM+k54OFra
  MvgGHcEcoYlNbI1kSm13rIZ9Hl39gVxcDJKEuWZ8t9KFdMaABHXNA/B1eUJ9mWFF
  Qwb7YEDvwOg4hYbkbgdoqXQwyRM9RdjErKX0DXEvwXVsve1/hOJP0imTS2Odh818
  owrNUklLoV7fKQMqlkiXEmdWrddAgTvVV+Ms4ysTK5gfR6M0L9+hwb3SIG++Q3Jk
  oerupaUmZJcCAwEAAaMnMCUwDgYDVR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsG
  AQUFBwMDMA0GCSqGSIb3DQEBCwUAA4IBAQCNm+LMY1jvng+jSCVLVs+kWyyBB9UG
  RqTA3UnoImzKbDJv4VGHRuNP83Li/w9Q61fBINQMjy5dGW8TMu6Yg9788t7kYH1x
  UTOJjRW5pYK2t4T2k7fjAbALox8d8VJTFCnCo7zX6x/yZ3rEcMAxTNr4NNpJUGE4
  SWyRFCrJvm+9GYO9xTWz+mMraMVM2MN103b/uFfvktwe6WJhdgySfuBE3BI1bk02
  xYGsS8ACLM2WkEdoyQ5Sc9Cdgw3ZBb5HZvj7UzJAMykJ9zYASUahejMiMZ+u8ZOD
  O++48iYu3Y3rOcq+zfEVE16LqF8bQkaMm4tcYCyeea67bWVCMO8+EzCu
  -----END CERTIFICATE-----
cosign:
  enabled: true
  key: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEVf5oJDgnvwGJ+74iZiK+YPdovKXk
    N1QJeDI89gze8x6zDGPye+qEZbzKsdJ6yvlrZ3NAIblQQA10N5t7nfB00A==
    -----END PUBLIC KEY-----
resources:
   limits:
     cpu: 1000m
     memory: 512Mi
   requests:
     cpu: 600m
     memory: 512Mi
serviceAccount:
  create: false
  name:

# Can be used to authenticate to:
# ACR -> oras.authProviders.azureWorkloadIdentityEnabled
# Key Vault -> akvCertConfig.enabled
azureWorkloadIdentity:
  clientId:

akvCertConfig:
  enabled: false
  vaultName:
  cert1Name:
  cert2Name:
  tenantId:

oras:
  authProviders:
    azureWorkloadIdentityEnabled: false
    k8secretsEnabled: false
    awsEcrBasicEnabled: false

provider:
  auth: ""                  # tls, mtls
  tls:
    skipVerify: true        # skip TLS verification
    crt: ""                 # crt used by ratify (httpserver)
    key: ""                 # key used by ratify (httpserver)
    cabundle: ""            # base64 encoded CA bundle used for the 'caBundle' property for the ratify provider within gatekeeper

podAnnotations: {}
podLabels: {}
enableRuntimeDefaultSeccompProfile: true

rbac:
  create: true
  
upgradeCRDs:
  enabled: true
  extraRules: []

crds:
  affinity: {}
  tolerations: []
  nodeSelector: {kubernetes.io/os: linux}
  resources: {}
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532
