# permissions for end users to edit certificatestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificatestore-editor-role
rules:
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores/status
  verbs:
  - get
