# permissions for end users to view certificatestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificatestore-viewer-role
rules:
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - certificatestores/status
  verbs:
  - get
