# permissions for end users to edit namespacedstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: namespacedstore-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ratify
    app.kubernetes.io/part-of: ratify
    app.kubernetes.io/managed-by: kustomize
  name: namespacedstore-editor-role
rules:
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - namespacedstores/status
  verbs:
  - get
