apiVersion: v1
kind: Secret
metadata:
  name: wabbit-networks-crt
data:
  wabbit-networks.crt: <base64 encode of crt file contents>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratify
  labels:
    app: ratify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratify
  template:
    metadata:
      labels:
        app: ratify
    spec:
      containers:
        - name: ratify
          image: deislabs/ratify:v1
          imagePullPolicy: Never #to access the local registry for the image
          ports:
            - containerPort: 6001
          volumeMounts:
          - mountPath: "/usr/local/wa-certs"
            name: wabbit-networks-crt
            readOnly: true
      volumes:
        - name: wabbit-networks-crt
          secret:
            secretName: wabbit-networks-crt
---
apiVersion: v1
kind: Service
metadata:
  name: ratify-svc
  labels:
    app: ratify
spec:
  type: ClusterIP
  selector:
    app: ratify
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 6001
      targetPort: 6001
