apiVersion: config.ratify.deislabs.io/v1beta1
kind: NamespacedVerifier
metadata:
  name: verifier-sbom
spec:
  name: sbom
  artifactTypes: application/spdx+json
  parameters: 
    nestedReferences: application/vnd.cncf.notary.signature