apiVersion: config.ratify.deislabs.io/v1beta1
kind: NamespacedVerifier
metadata:
  name: verifier-sbom
spec:
  name: sbom
  version: 2.0.0-alpha.1
  artifactTypes: application/spdx+json
  parameters:
    disallowedLicenses:
    - Zlib
    disallowedPackages:
    - name: musl-utils
      version: 1.2.3-r4
    nestedReferences: application/vnd.cncf.notary.signature