apiVersion: config.ratify.deislabs.io/v1alpha1
kind: Verifier
metadata:
  name: verifier-sample
spec:
  name: sample
  artifactTypes: application/spdx+json
  source: noelfdpo.azurecr.io/sample-plugin:v1
  parameters: {}
