apiVersion: config.ratify.deislabs.io/v1alpha1
kind: Verifier
metadata:
  name: verifier-license-checker
spec:
  name: licensechecker
  artifactTypes: application/vnd.ratify.spdx.v0
  parameters: 
    allowedLicenses: 
    - MIT
    - GPL-2.0-only
    - OpenSSL
    - BSD-2-Clause AND BSD-3-Clause
    - Zlib
    - MPL-2.0 AND MIT
    - ISC