{{- if .Values.akvCertConfig.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "ratify.akv.secretProviderClassName" . }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: {{ required "vaultName must be provided when AKV cert config is enabled" .Values.akvCertConfig.vaultName  }}
    objects:  |
      array:
        - |
          objectName: {{ required "certName must be provided when AKV cert config is enabled" .Values.akvCertConfig.certName  }}
          objectType: cert
          objectAlias: ratify-test.crt
    tenantId: {{ required "tenantId must be provided when AKV cert config is enabled" .Values.akvCertConfig.tenantId  }}
{{ end }}