apiVersion: mutations.gatekeeper.sh/v1beta1
kind: Assign
metadata:
  name: mutate-pod-image
spec:
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
    excludedNamespaces:
      - "gatekeeper-system"
      {{- if ne .Release.Namespace "gatekeeper-system"}}
      - {{ .Release.Namespace }}
      {{- end }}
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  location: "spec.containers[name:*].image"
  parameters:
    assign:
      externalData:
        provider: ratify-mutation-provider

---
apiVersion: mutations.gatekeeper.sh/v1beta1
kind: Assign
metadata:
  name: mutate-deployment-image
spec:
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["apps"]
      kinds: ["Deployment"]
    excludedNamespaces:
      - "gatekeeper-system"
      {{- if ne .Release.Namespace "gatekeeper-system"}}
      - {{ .Release.Namespace }}
      {{- end }}
  applyTo:
  - groups: ["apps"]
    kinds: ["Deployment"]
    versions: ["v1"]
  location: "spec.template.spec.containers[name:*].image"
  parameters:
    assign:
      externalData:
        provider: ratify-mutation-provider