apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ratify.fullname" . }}-configuration
data:
  config.json: |
    {
      "stores": {
        "version": "1.0.0",
        "plugins": [
            {
                "name": "oras"
                {{- if .Values.cosign.enabled }}
                ,
                "cosign-enabled": true
                {{- end }}
                {{- if .Values.oras.authProviders.azurewi }}
                ,
                "auth-provider": {
                    "name": "azure-wi"
                }
                {{- end }}
                {{- if .Values.oras.authProviders.k8secrets }}
                ,
                "auth-provider": {
                    "name": "k8secrets"
                }
                {{- end }}
            }
        ]
      },
      "policies": {
          "version": "1.0.0",
          "artifactVerificationPolicies": {
              "application/vnd.cncf.notary.v2.signature": "any"
          }
      },
      "verifiers": {
          "version": "1.0.0",
          "plugins": [
            {
                "name":"notaryv2",
                "artifactTypes" : "application/vnd.cncf.notary.v2.signature",
                "verificationCerts": [
                    "/usr/local/ratify-certs/ratify-test.crt"
                  ]
            {{- if .Values.cosign.enabled }}
            },
            {
                "name": "cosign",
                "artifactTypes": "org.sigstore.cosign.v1",
                "key": "/usr/local/ratify-certs/cosign.pub"
            {{- end }}
            }
          ]
      }
    }