apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ratify.fullname" . }}-configuration
data:
  config.json: |
    {
      "stores": {
        "version": "1.0.0",
        "plugins": [
            {
                "name": "oras",
                "cosign-enabled": true,
                "localCachePath": "./local_oras_cache"
            }
        ]
      },
      "policies": {
          "version": "1.0.0",
          "artifactVerificationPolicies": {
              "application/vnd.cncf.notary.v2": "any"
          }
      },
      "verifiers": {
          "version": "1.0.0",
          "plugins": [
            {
                "name":"sbom",
                "artifactTypes":"org.example.sbom.v0",
                "nestedReferences": "application/vnd.cncf.notary.v2.signature"
            }
          ]
      }
    }
