{{- if .Values.notaryCert }} 
apiVersion: config.ratify.deislabs.io/v1beta1
kind: CertificateStore
metadata:
  name: {{ include "ratify.fullname" . }}-notary-inline-cert
spec:
  provider: inline
  parameters:
    value: {{ .Values.notaryCert | quote }}
{{- end }}
