{{- if .Values.notationCert }} 
apiVersion: config.ratify.deislabs.io/v1beta1
kind: CertificateStore
metadata:
  name: {{ include "ratify.fullname" . }}-notation-inline-cert
  namespace: default
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
spec:
  provider: inline
  parameters:
    value: {{ .Values.notationCert | quote }}
{{- end }}
