{{ include "ratify.providerGKVersion" . }}
kind: Provider
metadata:
  name: ratify-provider
spec:
  url: https://{{ include "ratify.fullname" .}}.{{ .Release.Namespace }}:6001/ratify/gatekeeper/v1/verify
  timeout: 7
  caBundle: {{ required "You must provide .Values.provider.tls.cabundle" .Values.provider.tls.cabundle }}
---
{{ include "ratify.providerGKVersion" . }}
kind: Provider
metadata:
  name: ratify-mutation-provider
spec:
  url: https://{{ include "ratify.fullname" .}}.{{ .Release.Namespace }}:6001/ratify/gatekeeper/v1/mutate
  timeout: 1
  caBundle: {{ required "You must provide .Values.provider.tls.cabundle" .Values.provider.tls.cabundle }}