apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ratify.fullname" . }}-rego-policy
data:
  policy.rego: |
    package ratify.policy
    default valid := false
    valid {
      not failed_verify(input)
    }
    # The verification requires all reports to have isSuccess as true.
    failed_verify(reports) {
      [path, value] := walk(reports)
      value == false
      path[count(path) - 1] == "isSuccess"
    }
    # The verification requires at least one report for each artifact.
    failed_verify(reports) {
      [path, value] := walk(reports)
      path[count(path) - 1] == "verifierReports"
      count(value) == 0
    }