apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-certificate
data:
  ratify-test.crt: {{ .Values.ratifyTestCert | b64enc | quote }}
  {{- if .Values.cosign.enabled }}
  cosign.pub: {{ .Values.cosign.key | b64enc | quote }}
  {{- end }}
