apiVersion: config.ratify.deislabs.io/v1alpha1
kind: Store
metadata:
  name: store-oras
spec:
  name: oras
  parameters:
    {{- if .Values.cosign.enabled }}
    cosignEnabled: true
    {{- end }}
    {{- if .Values.oras.authProviders.azureWorkloadIdentityEnabled }}
    authProvider:
      name: azureWorkloadIdentity
    {{- end }}
    {{- if .Values.oras.authProviders.azureManagedIdentityEnabled }}
    authProvider:
      name: azureManagedIdentity
      clientID: {{ .Values.azureManagedIdentity.clientId }}
    {{- end }}
    {{- if .Values.oras.authProviders.k8secretsEnabled }}
    authProvider:
      name: k8Secrets
      serviceAccountName: {{ include "ratify.serviceAccountName" . }} 
    {{- end }}
    {{- if .Values.oras.authProviders.awsEcrBasicEnabled }}
    authProvider:
      name: awsEcrBasic
    {{- end }}