apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8ssignedimages
spec:
  crd:
    spec:
      names:
        kind: K8sSignedImages
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8ssignedimages
        violation[{"msg": msg}] {
          images := [img | img = input.review.object.spec.containers[_].image]
          response := external_data({"provider": "ratify-provider", "keys": images})
          response_with_error(response)
          msg := sprintf("Image verification failed : %v", [response])
        }
        response_with_error(response) {
          count(response.errors) > 0
          errs := response.errors[_]
          contains(errs[1], "_invalid")
        }
        response_with_error(response) {
          count(response.system_error) > 0
        }
