apiVersion: config.ratify.deislabs.io/v1alpha1
kind: Verifier
metadata:
  name: verifier-notary
spec:
  name: notaryv2
  artifactTypes: application/vnd.cncf.notary.signature
  parameters:
    {{- if .Values.akvCertConfig.enabled }}
    verificationCertStores:
      certs:
        - certstore-akv
    {{- else }}
    verificationCerts:
      - /usr/local/ratify-certs/notary/truststore
    {{- end }}    
    trustPolicyDoc:
      version: "1.0"
      trustPolicies:
        - name: default
          registryScopes:
            - "*"
          signatureVerification:
            level: strict
          trustStores:
            - ca:certs
          trustedIdentities:
            - "*"
---
{{- if .Values.cosign.enabled }}
apiVersion: config.ratify.deislabs.io/v1alpha1
kind: Verifier
metadata:
  name: verifier-cosign
spec:
  name: cosign
  artifactTypes: org.sigstore.cosign.v1
  parameters:
    key: /usr/local/ratify-certs/cosign/cosign.pub
{{- end }}