{{- $fullname := include "ratify.fullname" . -}}
---
apiVersion: config.ratify.deislabs.io/v1beta1
kind: Verifier
metadata:
  name: verifier-notation
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
spec:
  name: notation
  artifactTypes: application/vnd.cncf.notary.signature
  parameters:
    verificationCertStores:
      certs:
        {{- if .Values.akvCertConfig.enabled }}
        - certstore-akv
        {{- else }}
          {{- if .Values.notationCert }}
            {{- if .Values.notationCerts }}
            {{- fail "please specify notation certs with .Values.notationCerts, single certificate .Values.notationCert is deprecated, will soon be removed." }}
            {{- end -}}
        - {{$fullname}}-notation-inline-cert
          {{- end }} 
          {{-  range $i, $cert := .Values.notationCerts }}
        - {{$fullname}}-notation-inline-cert-{{$i}}
          {{- end }} 
        {{- end }}
    trustPolicyDoc:
      version: "1.0"
      trustPolicies:
        - name: default
          registryScopes:
            - "*"
          signatureVerification:
            level: strict
          trustStores:
            - ca:certs
          trustedIdentities:
            - "*"
---
{{- if .Values.cosign.enabled }}
apiVersion: config.ratify.deislabs.io/v1beta1
kind: Verifier
metadata:
  name: verifier-cosign
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "5"
spec:
  name: cosign
  artifactTypes: application/vnd.dev.cosign.artifact.sig.v1+json
  parameters:
    key: /usr/local/ratify-certs/cosign/cosign.pub
{{- end }}