# Configuration for referrer stores
stores:
  version: 1.0.0
  plugins:
    - name: oras
      useHttp: true
      cosign-enabled: true
      localCachePath: ./local_oras_cache
# Configuration for policy
policies:
  version: 1.0.0
  artifactVerificationPolicies:
    application/vnd.cncf.notary.v2: any
    application/x.example.sbom.v0: all
# Configuration for verifiers
verifiers:
  version: 1.0.0
  plugins:
    - name: notaryv2
      artifactTypes: org.cncf.notary.v2
      verificationCerts:
        - /path/to/cert
    - name: sbom
      artifactTypes: application/x.example.sbom.v0
      nestedReferences: application/vnd.cncf.notary.v2
    - name: cosign
      artifactTypes: org.sigstore.cosign.v1
      key: /path/to/public/key
