apiVersion: config.ratify.deislabs.io/v1beta1
kind: NamespacedPolicy # NamespacedPolicy only applies to specified namespace.
metadata:
  name: "ratify-policy" # metadata.name MUST be set to ratify-policy since v1beta1.
spec:
  type: "rego-policy" # Ensure that spec.type is either 'rego-policy' or 'config-policy' in v1beta1.
  parameters:
    passthroughEnabled: false
    policy: |
      package ratify.policy

      default valid := false

      # all artifacts MUST be valid
      valid {
        not failed_verify(input)
      }

      # all reports MUST pass the verification
      failed_verify(reports) {
        [path, value] := walk(reports)
        value == false
        path[count(path) - 1] == "isSuccess"
      }

      # each artifact MUST have at least one report
      failed_verify(reports) {
        [path, value] := walk(reports)
        path[count(path) - 1] == "verifierReports"
        count(value) == 0
      }
