name: pr_to_main

on:
  push:
    branches:
      - 'dev'

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: create pull request with reposync action
        id: open-pr
        uses: repo-sync/pull-request@7e79a9f5dc3ad0ce53138f01df2fad14a04831c5 #v2.12.1
        with:
          destination_branch: main
          pr_title: "chore: automated PR to main ${{ steps.date.outputs.date }}"
          pr_body: "Automated Pull Request to main branch"
