name: Release Ratify

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
          
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Goreleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --rm-dist
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate SBOM
      run: |
        curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
        chmod +x $RUNNER_TEMP/sbom-tool
        $RUNNER_TEMP/sbom-tool generate -b ./buildOutput -bc . -pn ratify -pv ${{env.GITHUB_REF_NAME}}-${{env.GITHUB_SHA}} -ps Microsoft -nsb https://microsoft.com -V Verbose

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        path: buildOutput